import type { Metadata } from "next";
import "./globals.css";

const basePath =
  process.env.NODE_ENV === "production" ? "/chart-render" : "";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" >
      <head>
        <style>{`
          @font-face {
            font-family: "Epsilon";
            src: url("${basePath}/fonts/w_Epsilon.ttf") format("truetype");
            font-weight: 400;
            font-style: normal;
            font-display: swap;
          }
        `}</style>
      </head>

      <body>{children}</body>
    </html>
  );
}